### ISSUE TITLE
Non existent parent route for a menu link

### ISSUE THREAD

**Issue by aleevas** [open-y-subprojects/openy_daxko_gxp_syncer#7]
This issue related to [MAINTAIN-160](https://openy.atlassian.net/browse/MAINTAIN-160)

Currently we have for the "GroupEx Pro Daxko API Syncer settings" not esisten parent route.
As result we donlt see this link item in the admin menu
Need to fix that
![MAINTAIN-160LinkNotPresent](https://user-images.githubusercontent.com/744406/138936946-e132ab6d-9cdf-46ae-8c51-58d8d0696efd.png)

**Comment by podarok** [comment]
Fixed in https://github.com/open-y-subprojects/openy_daxko_gxp_syncer/pull/9
